// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ticyyepbetskexuifnma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpY3l5ZXBiZXRza2V4dWlmbm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTcwMTMsImV4cCI6MjA3MzU3MzAxM30.vDhWoRK-Y4DRj2Y4_ESMURkAX8NxlVUXHlAiVwkuVp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});